In [1]:
# project: p12
# submitter: Smwells3
# partner: none

In [2]:
import time, requests, os, sqlite3, math, collections, copy, json
import pandas as pd
from pandas import DataFrame, Series
from collections import defaultdict
from bs4 import BeautifulSoup

In [3]:
def download(filename, url):
    if os.path.exists(filename):
        return (str(filename) + " already exists!")
    r = requests.get(url)
    urltxt = r.text
    f = open(filename, "w")
    f.write(urltxt)
    f.close()
    return (str(filename) + " created!")

In [4]:
download("countries.json", "https://raw.githubusercontent.com/msyamkumar/cs220-f20-projects/master/p12/countries.json")

'countries.json already exists!'

In [5]:
countries = pd.read_json("countries.json")
countries.head()

,area,birth-rate,coastline,continent,country,death-rate,gdp-per-capita,infant-mortality,literacy,net-migration,phones,population,region
0,756950,15.23,0.85,South America,Chile,5.81,9900,8.80,"96,2",0.00,"213,0",16134219,LATIN AMER. & CARIB
1,665,17.80,24.21,Asia,Bahrain,4.14,16900,17.27,"89,1",1.05,"281,3",698585,NEAR EAST
2,22966,28.84,1.68,North America,Belize,5.72,4900,25.69,"94,1",0.00,"115,7",287730,LATIN AMER. & CARIB
3,582650,39.72,0.09,Africa,Kenya,14.02,1000,61.47,"85,1",-0.10,"8,1",34707817,SUB-SAHARAN AFRICA
4,11854,33.05,3.12,Australia,Marshall Islands,4.78,1600,29.45,"93,7",-6.04,"91,2",60422,OCEANIA

In [6]:
#q1
len(countries)

174

In [7]:
#q2
countries["population"].sum()

6261901793

In [8]:
download("capitals.json","https://raw.githubusercontent.com/msyamkumar/cs220-f20-projects/master/p12/capitals.json")

'capitals.json already exists!'

In [9]:
capitals = pd.read_json("capitals.json")
capitals.head()

       country       capital   latitude  longitude
0  Afghanistan         Kabul  34.516667  69.183333
1      Albania        Tirana  41.316667  19.816667
2      Algeria       Algiers  36.750000   3.050000
3     Anguilla    The Valley  18.216667 -63.050000
4    Argentina  Buenos Aires -34.583333 -58.666667

In [10]:
#q3
sorted(list(capitals["capital"]))

['Abu Dhabi',
 'Abuja',
 'Accra',
 'Addis Ababa',
 'Algiers',
 'Amman',
 'Amsterdam',
 'Ankara',
 'Antananarivo',
 'Apia',
 'Ashgabat',
 'Asmara',
 'Astana',
 'Asuncion',
 'Athens',
 'Baghdad',
 'Baku',
 'Bamako',
 'Bangkok',
 'Beijing',
 'Beirut',
 'Belmopan',
 'Berlin',
 'Bern',
 'Bishkek',
 'Bissau',
 'Bogota',
 'Brasilia',
 'Bridgetown',
 'Brussels',
 'Bucharest',
 'Budapest',
 'Buenos Aires',
 'Bujumbura',
 'Cairo',
 'Canberra',
 'Caracas',
 'Castries',
 'Chisinau',
 'Colombo',
 'Conakry',
 'Copenhagen',
 'Dakar',
 'Damascus',
 'Dar es Salaam',
 'Dhaka',
 'Djibouti',
 'Doha',
 'Dublin',
 'Dushanbe',
 'Freetown',
 'Gaborone',
 'George Town',
 'Georgetown',
 'Guatemala City',
 'Hagatna',
 'Hamilton',
 'Hanoi',
 'Harare',
 'Havana',
 'Helsinki',
 'Islamabad',
 'Jakarta',
 'Jamestown',
 'Jerusalem',
 'Kabul',
 'Kampala',
 'Kathmandu',
 'Khartoum',
 'Kigali',
 'Kingston',
 'Kingstown',
 'Kuala Lumpur',
 'Kuwait City',
 'Kyiv',
 'La Paz',
 'Libreville',
 'Lilongwe',
 'Lima',
 'Lisbon',
 'Ljubljana',
 'Lome',
 'London',
 'Lusaka',
 'Luxembourg',
 'Madrid',
 'Majuro',
 'Malabo',
 'Male',
 'Managua',
 'Manama',
 'Manila',
 'Maputo',
 'Maseru',
 'Mbabane',
 'Melekeok',
 'Mexico City',
 'Minsk',
 'Mogadishu',
 'Monaco',
 'Monrovia',
 'Montevideo',
 'Moroni',
 'Moscow',
 'Muscat',
 'Nairobi',
 'New Delhi',
 'Niamey',
 'Nouakchott',
 'Noumea',
 'Nuku’alofa',
 'N’Djamena',
 'Oranjestad',
 'Oslo',
 'Ottawa',
 'Ouagadougou',
 'Panama City',
 'Papeete',
 'Paramaribo',
 'Paris',
 'Phnom Penh',
 'Port Louis',
 'Port Moresby',
 'Port-Vila',
 'Port-au-Prince',
 'Porto-Novo',
 'Prague',
 'Praia',
 'Pretoria',
 'Quito',
 'Rabat',
 'Reykjavik',
 'Riga',
 'Riyadh',
 'Rome',
 'Roseau',
 'Saint George’s',
 'San Jose',
 'San Juan',
 'San Marino',
 'San Salvador',
 'Sanaa',
 'Santiago',
 'Santo Domingo',
 'Singapore',
 'Sofia',
 'Stockholm',
 'Suva',
 'Taipei',
 'Tallinn',
 'Tashkent',
 'Tbilisi',
 'Tegucigalpa',
 'Tehran',
 'The Valley',
 'Thimphu',
 'Tirana',
 'Tokyo',
 'Tripoli',
 'Tunis',
 'Ulaanbaatar',
 'Vaduz',
 'Valletta',
 'Victoria',
 'Vienna',
 'Vientiane',
 'Vilnius',
 'Warsaw',
 'Washington, D.C.',
 'Wellington',
 'Windhoek',
 'Yaounde',
 'Yerevan',
 'Zagreb']

In [11]:
#q4
next(iter(capitals[capitals["country"] == "Italy"]["capital"]))

'Rome'

In [12]:
#q5
next(iter(capitals[capitals["capital"] == "Brussels"]["country"]))

'Belgium'

In [13]:
#q6
def get_latitude(country):
    latitude = next(iter(capitals[capitals["country"] == country]["latitude"]))
    return latitude
country_list = []
for country in countries['country']:
    country_list.append(country)
south_sorted = sorted(country_list, key=get_latitude)
south_sorted[:7]

['New Zealand',
 'Australia',
 'Uruguay',
 'Argentina',
 'Chile',
 'Lesotho',
 'Swaziland']

In [14]:
#q7
sorted(country_list, key=get_latitude, reverse=True)[:10]

['Iceland',
 'Finland',
 'Norway',
 'Estonia',
 'Sweden',
 'Latvia',
 'Russia',
 'Denmark',
 'Lithuania',
 'Belarus']

In [15]:
#q8
def get_area(country):
    area = next(iter(countries[countries["country"] == country]["area"]))
    return area    
land_locked = countries[countries["coastline"] == 0]
asian_land_locked = land_locked[land_locked["continent"] == "Asia"]
asian_ll = []
for country in asian_land_locked["country"]:
    asian_ll.append(country)
sorted(asian_ll, key=get_area)[0]

'Bhutan'

In [16]:
#q9
coastal = countries[countries["coastline"] != 0]
asian_coastal = coastal[coastal["continent"] == "Asia"]
coastal_asian = []
for country in asian_coastal["country"]:
    coastal_asian.append(country)
sorted(coastal_asian, key=get_area, reverse=True)[0]

'China'

In [17]:
def get_population(country):
    population = next(iter(countries[countries["country"] == country]["population"]))
    return population

In [18]:
#q10
south_american_coastal = coastal[coastal["continent"] == "South America"]
coastal_south_american = []
for country in south_american_coastal["country"]:
    coastal_south_american.append(country)
sorted(coastal_south_american, key=get_population)[0]

'Suriname'

In [19]:
#formula from http://www.movable-type.co.uk/scripts/gis-faq-5.1.html
def distance(lon1, lat1, lon2, lat2):
    lon1 *= math.pi/180
    lon2 *= math.pi/180
    lat1 *= math.pi/180
    lat2 *= math.pi/180
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = math.sin(dlat/2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon/2)**2
    c = 2 * math.asin(min(1,math.sqrt(a)))
    d = 3956 * c
    return d

In [20]:
#q11
distance(-89.411893, 43.070231, -89.384113, 43.074645)

1.433899492072933

In [21]:
def distance_countries(country1, country2):
    lat1 = next(iter(capitals[capitals["country"] == country1]["latitude"]))
    lon1 = next(iter(capitals[capitals["country"] == country1]["longitude"]))
    lat2 = next(iter(capitals[capitals["country"] == country2]["latitude"]))
    lon2 = next(iter(capitals[capitals["country"] == country2]["longitude"]))
    return distance(lon1, lat1, lon2, lat2)

In [22]:
#q12
distance_countries("Germany", "Norway")

520.8581822565818

In [23]:
def distance_dict(country_list): 
    all_distance = defaultdict(dict)
    for country in country_list:
        all_distance[country] = {}
        for each in country_list:
            if each == country:
                all_distance[country][each] = "NaN"
            else:
                all_distance[country][each] = distance_countries(each, country)
    return dict(all_distance)

In [24]:
#q13
data = distance_dict(["Italy", "United Kingdom", "Germany"])
DataFrame(data)

                  Italy United Kingdom  Germany
Italy               NaN        888.293  734.274
United Kingdom  888.293            NaN  576.472
Germany         734.274        576.472      NaN

In [25]:
north_american = list(countries[countries["continent"] == "North America"]["country"])

In [26]:
#q14
data = distance_dict(north_american)
na_data = DataFrame(data)
na_data

,Belize,Jamaica,Bermuda,Saint Vincent and the Grenadines,Cuba,Saint Lucia,United States,Anguilla,Grenada,Dominican Republic,...,Guatemala,Panama,El Salvador,Mexico,Honduras,Aruba,Puerto Rico,Canada,Cayman Islands,Haiti
Belize,NaN,789.018,1819.62,1855.89,580.312,1858.26,1653.24,1691.19,1838.29,1242.17,...,215.765,843.681,246.8,695.786,240.659,1291.29,1489.93,2085.59,504.276,1083.02
Jamaica,789.018,NaN,1237.53,1089.01,503.397,1083.91,1441.94,902.263,1083.74,453.609,...,938.175,650.085,875.148,1462.8,741.564,588.467,701.235,1894.05,312.971,295.158
Bermuda,1819.62,1237.53,NaN,1341.31,1243.92,1284.73,822.389,977.199,1410.21,1005.54,...,2025.95,1865.92,2004.09,2298.4,1890.14,1404.73,957.565,1077.95,1363.59,1058.86
Saint Vincent and the Grenadines,1855.89,1089.01,1341.31,NaN,1545.84,61.5809,2022.64,371.522,82.9844,684.148,...,1965.34,1273.65,1878.75,2545.04,1745.12,595.055,491.404,2385.08,1401.88,826.84
Cuba,580.312,503.397,1243.92,1545.84,NaN,1530.12,1133.13,1290.67,1553.37,864.914,...,792.704,994.595,789.61,1108.62,699.074,1090.16,1095.11,1584.38,270.765,719.41
Saint Lucia,1858.26,1083.91,1284.73,61.5809,1530.12,NaN,1975.32,321.317,143.779,665.537,...,1973.85,1300.64,1889.46,2544.24,1755.08,615.61,458.352,2332.87,1395.98,813.474
United States,1653.24,1441.94,822.389,2022.64,1133.13,1975.32,NaN,1654.2,2075.38,1472.54,...,1866.2,2071.56,1891.36,1883.03,1820.86,1869.85,1553.3,455.959,1377.27,1432.65
Anguilla,1691.19,902.263,977.199,371.522,1290.67,321.317,1654.2,NaN,434.495,449.237,...,1834.25,1275.94,1762.04,2355.35,1626.34,608.94,201.719,2013.61,1200.37,608.615
Grenada,1838.29,1083.74,1410.21,82.9844,1553.37,143.779,2075.38,434.495,NaN,700.424,...,1939.48,1225.57,1850.18,2530.68,1717.77,559.736,529.885,2445.61,1396.43,834.542
Dominican Republic,1242.17,453.609,1005.54,684.148,864.914,665.537,1472.54,449.237,700.424,NaN,...,1389.31,920.103,1321.13,1907.93,1185.94,410.915,247.766,1890.3,752.259,159.393
Nicaragua,391.199,748.702,1945.78,1687.32,800.429,1702.33,1932.13,1600.47,1653.52,1172.53,...,333.951,505.565,226.079,992.629,150.544,1094.03,1409.09,2380.38,591.018,1025.96
Barbados,1961.54,1191.31,1364.22,107.615,1641.24,111.728,2073,420.554,161.006,776.923,...,2072.49,1379.01,1986.19,2649.59,1852.46,702.429,568.887,2422.13,1503.85,923.855
Dominica,1817.32,1035.27,1191.72,150.1,1466.6,93.6513,1883.18,229.022,225.622,602.524,...,1941.38,1298.93,1860.36,2498.03,1725.17,609.599,380.631,2239.29,1345.05,755.74
Costa Rica,594.84,740.189,1973.9,1562.02,917.409,1583.42,2046.18,1518.53,1520.31,1116.32,...,541.13,316.992,432.618,1198.95,357.095,967.923,1337.72,2499.87,671.345,984.609
Guatemala,215.765,938.175,2025.95,1965.34,792.704,1973.85,1866.2,1834.25,1939.48,1389.31,...,NaN,838.26,108.516,658.722,223.593,1381.94,1635.34,2295.11,684.163,1232.62
Panama,843.681,650.085,1865.92,1273.65,994.595,1300.64,2071.56,1275.94,1225.57,920.103,...,838.26,NaN,731.275,1495.56,628.952,689.345,1112.53,2527.01,724.106,817.813
El Salvador,246.8,875.148,2004.09,1878.75,789.61,1889.46,1891.36,1762.04,1850.18,1321.13,...,108.516,731.275,NaN,767.011,135.768,1291.13,1565.05,2327.81,645.741,1166.81
Mexico,695.786,1462.8,2298.4,2545.04,1108.62,2544.24,1883.03,2355.35,2530.68,1907.93,...,658.722,1495.56,767.011,NaN,869.188,1986.79,2153.85,2237.08,1155.73,1749.13
Honduras,240.659,741.564,1890.14,1745.12,699.074,1755.08,1820.86,1626.34,1717.77,1185.94,...,223.593,628.952,135.768,869.188,NaN,1159.46,1429.52,2264.43,526.867,1032.14
Aruba,1291.29,588.467,1404.73,595.055,1090.16,615.61,1869.85,608.94,559.736,410.915,...,1381.94,689.345,1291.13,1986.79,1159.46,NaN,486.425,2295.86,886.781,442.675
Puerto Rico,1489.93,701.235,957.565,491.404,1095.11,458.352,1553.3,201.719,529.885,247.766,...,1635.34,1112.53,1565.05,2153.85,1429.52,486.425,NaN,1940.31,998.695,407.056
Canada,2085.59,1894.05,1077.95,2385.08,1584.38,2332.87,455.959,2013.61,2445.61,1890.3,...,2295.11,2527.01,2327.81,2237.08,2264.43,2295.86,1940.31,NaN,1832.28,1866.19
Cayman Islands,504.276,312.971,1363.59,1401.88,270.765,1395.98,1377.27,1200.37,1396.43,752.259,...,684.163,724.106,645.741,1155.73,526.867,886.781,998.695,1832.28,NaN,593.406
Haiti,1083.02,295.158,1058.86,826.84,719.41,813.474,1432.65,608.615,834.542,159.393,...,1232.62,817.813,1166.81,1749.13,1032.14,442.675,407.056,1866.19,593.406,NaN

In [27]:
#q15
copy_na_data = copy.copy(na_data)
avg_distance = defaultdict(float)
for country in north_american:
    for data in copy_na_data[country]:
        if data == "NaN":
            copy_na_data[country][country] = 0
    avg_distance[country] = copy_na_data[country].mean()
def get_avg(country):
    return avg_distance[country]
sorted(north_american, key=get_avg)[0]

'Jamaica'

In [28]:
#q16
sorted(north_american, key=get_avg, reverse=True)[0]

'Canada'

In [29]:
#q17
min_distance = na_data.astype(float).min()
min_idx = na_data.astype(float).idxmin()
nearest = defaultdict(dict)
distance = defaultdict(float)
for country in na_data:
    nearest[country] = min_idx[country]
    distance[country] = min_distance[country]
DataFrame({"nearest": nearest, "distance": distance})

                                                           nearest    distance
Belize                                                   Guatemala  215.765123
Jamaica                                                      Haiti  295.158445
Bermuda                                              United States  822.389478
Saint Vincent and the Grenadines                       Saint Lucia   61.580891
Cuba                                                Cayman Islands  270.765230
Saint Lucia                       Saint Vincent and the Grenadines   61.580891
United States                                               Canada  455.959281
Anguilla                                               Puerto Rico  201.719030
Grenada                           Saint Vincent and the Grenadines   82.984426
Dominican Republic                                           Haiti  159.393141
Nicaragua                                                 Honduras  150.543884
Barbados                          Saint Vincent and the Grenadines  107.614568
Dominica                                               Saint Lucia   93.651335
Costa Rica                                               Nicaragua  211.258834
Guatemala                                              El Salvador  108.515759
Panama                                                  Costa Rica  316.992467
El Salvador                                              Guatemala  108.515759
Mexico                                                   Guatemala  658.722264
Honduras                                               El Salvador  135.767633
Aruba                                           Dominican Republic  410.914762
Puerto Rico                                               Anguilla  201.719030
Canada                                               United States  455.959281
Cayman Islands                                                Cuba  270.765230
Haiti                                           Dominican Republic  159.393141

In [30]:
#q18
max_distance = na_data.astype(float).max()
max_idx = na_data.astype(float).idxmax()
furthest = defaultdict(dict)
distance = defaultdict(float)
for country in na_data:
    furthest[country] = max_idx[country]
    distance[country] = max_distance[country]
DataFrame({"furthest": furthest, "distance": distance})

                                  furthest     distance
Belize                              Canada  2085.591134
Jamaica                             Canada  1894.046648
Bermuda                             Mexico  2298.396835
Saint Vincent and the Grenadines    Mexico  2545.035009
Cuba                              Barbados  1641.236050
Saint Lucia                         Mexico  2544.237348
United States                      Grenada  2075.376717
Anguilla                            Mexico  2355.347815
Grenada                             Mexico  2530.683480
Dominican Republic                  Mexico  1907.930275
Nicaragua                           Canada  2380.384387
Barbados                            Mexico  2649.594414
Dominica                            Mexico  2498.025650
Costa Rica                          Canada  2499.865223
Guatemala                           Canada  2295.113257
Panama                              Canada  2527.009335
El Salvador                         Canada  2327.814419
Mexico                            Barbados  2649.594414
Honduras                            Canada  2264.432575
Aruba                               Canada  2295.862288
Puerto Rico                         Mexico  2153.850522
Canada                              Panama  2527.009335
Cayman Islands                      Canada  1832.279943
Haiti                               Canada  1866.189819

In [31]:
#q19
death_rate = countries["death-rate"].describe()
birth_rate = countries["birth-rate"].describe()
DataFrame({"birth-rate": birth_rate, "death-rate": death_rate})

       birth-rate  death-rate
count  174.000000  174.000000
mean    22.463851    9.625172
std     11.278992    5.187143
min      8.250000    2.410000
25%     12.597500    6.027500
50%     20.010000    8.230000
75%     29.860000   11.715000
max     50.730000   29.740000

In [32]:
download('capitals.html', 'https://raw.githubusercontent.com/msyamkumar/cs220-f20-projects/master/p12/techslides-snapshot.html')

'capitals.html already exists!'

In [33]:
request = requests.get('https://raw.githubusercontent.com/msyamkumar/cs220-f20-projects/master/p12/techslides-snapshot.html')
request.raise_for_status()
soup = BeautifulSoup(request.text, "html.parser")
data_table = soup.find("table")
rows = data_table.find_all("tr")
data = data_table.find_all("tr")
data_dict = []

for each in range(len(data)):
    country = data[each].find_all("td")[0].get_text()
    if country not in country_list:
        pass
    data_dict.append({})
    data_dict[each]["country"] = country
    data_dict[each]["capital"] = data[each].find_all("td")[1].get_text()
    data_dict[each]["latitude"] = data[each].find_all("td")[2].get_text()
    data_dict[each]["longitude"] = data[each].find_all("td")[3].get_text()
data_dict = data_dict[1:]

In [34]:
data_list = []
for each in data_dict:
    if each["country"] in country_list:
        data_list.append(each)

In [35]:
file = open("my_capitals.json", "w")
json.dump(data_list, file)
file.close()

In [36]:
#q20
open("my_capitals.json", "r").read()

'[{"country": "Afghanistan", "capital": "Kabul", "latitude": "34.51666667", "longitude": "69.183333"}, {"country": "Albania", "capital": "Tirana", "latitude": "41.31666667", "longitude": "19.816667"}, {"country": "Algeria", "capital": "Algiers", "latitude": "36.75", "longitude": "3.05"}, {"country": "Anguilla", "capital": "The Valley", "latitude": "18.21666667", "longitude": "-63.05"}, {"country": "Argentina", "capital": "Buenos Aires", "latitude": "-34.58333333", "longitude": "-58.666667"}, {"country": "Armenia", "capital": "Yerevan", "latitude": "40.16666667", "longitude": "44.5"}, {"country": "Aruba", "capital": "Oranjestad", "latitude": "12.51666667", "longitude": "-70.033333"}, {"country": "Australia", "capital": "Canberra", "latitude": "-35.26666667", "longitude": "149.133333"}, {"country": "Austria", "capital": "Vienna", "latitude": "48.2", "longitude": "16.366667"}, {"country": "Azerbaijan", "capital": "Baku", "latitude": "40.38333333", "longitude": "49.866667"}, {"country": "Bahrain", "capital": "Manama", "latitude": "26.23333333", "longitude": "50.566667"}, {"country": "Bangladesh", "capital": "Dhaka", "latitude": "23.71666667", "longitude": "90.4"}, {"country": "Barbados", "capital": "Bridgetown", "latitude": "13.1", "longitude": "-59.616667"}, {"country": "Belarus", "capital": "Minsk", "latitude": "53.9", "longitude": "27.566667"}, {"country": "Belgium", "capital": "Brussels", "latitude": "50.83333333", "longitude": "4.333333"}, {"country": "Belize", "capital": "Belmopan", "latitude": "17.25", "longitude": "-88.766667"}, {"country": "Benin", "capital": "Porto-Novo", "latitude": "6.483333333", "longitude": "2.616667"}, {"country": "Bermuda", "capital": "Hamilton", "latitude": "32.28333333", "longitude": "-64.783333"}, {"country": "Bhutan", "capital": "Thimphu", "latitude": "27.46666667", "longitude": "89.633333"}, {"country": "Bolivia", "capital": "La Paz", "latitude": "-16.5", "longitude": "-68.15"}, {"country": "Botswana", "capital": "Gaborone", "latitude": "-24.63333333", "longitude": "25.9"}, {"country": "Brazil", "capital": "Brasilia", "latitude": "-15.78333333", "longitude": "-47.916667"}, {"country": "Bulgaria", "capital": "Sofia", "latitude": "42.68333333", "longitude": "23.316667"}, {"country": "Burkina Faso", "capital": "Ouagadougou", "latitude": "12.36666667", "longitude": "-1.516667"}, {"country": "Burundi", "capital": "Bujumbura", "latitude": "-3.366666667", "longitude": "29.35"}, {"country": "Cambodia", "capital": "Phnom Penh", "latitude": "11.55", "longitude": "104.916667"}, {"country": "Cameroon", "capital": "Yaounde", "latitude": "3.866666667", "longitude": "11.516667"}, {"country": "Canada", "capital": "Ottawa", "latitude": "45.41666667", "longitude": "-75.7"}, {"country": "Cape Verde", "capital": "Praia", "latitude": "14.91666667", "longitude": "-23.516667"}, {"country": "Cayman Islands", "capital": "George Town", "latitude": "19.3", "longitude": "-81.383333"}, {"country": "Chad", "capital": "N\\u2019Djamena", "latitude": "12.1", "longitude": "15.033333"}, {"country": "Chile", "capital": "Santiago", "latitude": "-33.45", "longitude": "-70.666667"}, {"country": "China", "capital": "Beijing", "latitude": "39.91666667", "longitude": "116.383333"}, {"country": "Colombia", "capital": "Bogota", "latitude": "4.6", "longitude": "-74.083333"}, {"country": "Comoros", "capital": "Moroni", "latitude": "-11.7", "longitude": "43.233333"}, {"country": "Costa Rica", "capital": "San Jose", "latitude": "9.933333333", "longitude": "-84.083333"}, {"country": "Croatia", "capital": "Zagreb", "latitude": "45.8", "longitude": "16"}, {"country": "Cuba", "capital": "Havana", "latitude": "23.11666667", "longitude": "-82.35"}, {"country": "Czech Republic", "capital": "Prague", "latitude": "50.08333333", "longitude": "14.466667"}, {"country": "Denmark", "capital": "Copenhagen", "latitude": "55.66666667", "longitude": "12.583333"}, {"country": "Djibouti", "capital": "Djibouti", "latitude": "11.58333333", "longitude": "43.15"}, {"country": "Dominica", "capital": "Roseau", "latitude": "15.3", "longitude": "-61.4"}, {"country": "Dominican Republic", "capital": "Santo Domingo", "latitude": "18.46666667", "longitude": "-69.9"}, {"country": "Ecuador", "capital": "Quito", "latitude": "-0.216666667", "longitude": "-78.5"}, {"country": "Egypt", "capital": "Cairo", "latitude": "30.05", "longitude": "31.25"}, {"country": "El Salvador", "capital": "San Salvador", "latitude": "13.7", "longitude": "-89.2"}, {"country": "Equatorial Guinea", "capital": "Malabo", "latitude": "3.75", "longitude": "8.783333"}, {"country": "Eritrea", "capital": "Asmara", "latitude": "15.33333333", "longitude": "38.933333"}, {"country": "Estonia", "capital": "Tallinn", "latitude": "59.43333333", "longitude": "24.716667"}, {"country": "Ethiopia", "capital": "Addis Ababa", "latitude": "9.033333333", "longitude": "38.7"}, {"country": "Fiji", "capital": "Suva", "latitude": "-18.13333333", "longitude": "178.416667"}, {"country": "Finland", "capital": "Helsinki", "latitude": "60.16666667", "longitude": "24.933333"}, {"country": "France", "capital": "Paris", "latitude": "48.86666667", "longitude": "2.333333"}, {"country": "French Polynesia", "capital": "Papeete", "latitude": "-17.53333333", "longitude": "-149.566667"}, {"country": "Gabon", "capital": "Libreville", "latitude": "0.383333333", "longitude": "9.45"}, {"country": "Georgia", "capital": "Tbilisi", "latitude": "41.68333333", "longitude": "44.833333"}, {"country": "Germany", "capital": "Berlin", "latitude": "52.51666667", "longitude": "13.4"}, {"country": "Ghana", "capital": "Accra", "latitude": "5.55", "longitude": "-0.216667"}, {"country": "Greece", "capital": "Athens", "latitude": "37.98333333", "longitude": "23.733333"}, {"country": "Grenada", "capital": "Saint George\\u2019s", "latitude": "12.05", "longitude": "-61.75"}, {"country": "Guam", "capital": "Hagatna", "latitude": "13.46666667", "longitude": "144.733333"}, {"country": "Guatemala", "capital": "Guatemala City", "latitude": "14.61666667", "longitude": "-90.516667"}, {"country": "Guinea", "capital": "Conakry", "latitude": "9.5", "longitude": "-13.7"}, {"country": "Guinea-Bissau", "capital": "Bissau", "latitude": "11.85", "longitude": "-15.583333"}, {"country": "Guyana", "capital": "Georgetown", "latitude": "6.8", "longitude": "-58.15"}, {"country": "Haiti", "capital": "Port-au-Prince", "latitude": "18.53333333", "longitude": "-72.333333"}, {"country": "Honduras", "capital": "Tegucigalpa", "latitude": "14.1", "longitude": "-87.216667"}, {"country": "Hungary", "capital": "Budapest", "latitude": "47.5", "longitude": "19.083333"}, {"country": "Iceland", "capital": "Reykjavik", "latitude": "64.15", "longitude": "-21.95"}, {"country": "India", "capital": "New Delhi", "latitude": "28.6", "longitude": "77.2"}, {"country": "Indonesia", "capital": "Jakarta", "latitude": "-6.166666667", "longitude": "106.816667"}, {"country": "Iran", "capital": "Tehran", "latitude": "35.7", "longitude": "51.416667"}, {"country": "Iraq", "capital": "Baghdad", "latitude": "33.33333333", "longitude": "44.4"}, {"country": "Ireland", "capital": "Dublin", "latitude": "53.31666667", "longitude": "-6.233333"}, {"country": "Israel", "capital": "Jerusalem", "latitude": "31.76666667", "longitude": "35.233333"}, {"country": "Italy", "capital": "Rome", "latitude": "41.9", "longitude": "12.483333"}, {"country": "Jamaica", "capital": "Kingston", "latitude": "18", "longitude": "-76.8"}, {"country": "Japan", "capital": "Tokyo", "latitude": "35.68333333", "longitude": "139.75"}, {"country": "Jordan", "capital": "Amman", "latitude": "31.95", "longitude": "35.933333"}, {"country": "Kazakhstan", "capital": "Astana", "latitude": "51.16666667", "longitude": "71.416667"}, {"country": "Kenya", "capital": "Nairobi", "latitude": "-1.283333333", "longitude": "36.816667"}, {"country": "Kuwait", "capital": "Kuwait City", "latitude": "29.36666667", "longitude": "47.966667"}, {"country": "Kyrgyzstan", "capital": "Bishkek", "latitude": "42.86666667", "longitude": "74.6"}, {"country": "Laos", "capital": "Vientiane", "latitude": "17.96666667", "longitude": "102.6"}, {"country": "Latvia", "capital": "Riga", "latitude": "56.95", "longitude": "24.1"}, {"country": "Lebanon", "capital": "Beirut", "latitude": "33.86666667", "longitude": "35.5"}, {"country": "Lesotho", "capital": "Maseru", "latitude": "-29.31666667", "longitude": "27.483333"}, {"country": "Liberia", "capital": "Monrovia", "latitude": "6.3", "longitude": "-10.8"}, {"country": "Libya", "capital": "Tripoli", "latitude": "32.88333333", "longitude": "13.166667"}, {"country": "Liechtenstein", "capital": "Vaduz", "latitude": "47.13333333", "longitude": "9.516667"}, {"country": "Lithuania", "capital": "Vilnius", "latitude": "54.68333333", "longitude": "25.316667"}, {"country": "Luxembourg", "capital": "Luxembourg", "latitude": "49.6", "longitude": "6.116667"}, {"country": "Madagascar", "capital": "Antananarivo", "latitude": "-18.91666667", "longitude": "47.516667"}, {"country": "Malawi", "capital": "Lilongwe", "latitude": "-13.96666667", "longitude": "33.783333"}, {"country": "Malaysia", "capital": "Kuala Lumpur", "latitude": "3.166666667", "longitude": "101.7"}, {"country": "Maldives", "capital": "Male", "latitude": "4.166666667", "longitude": "73.5"}, {"country": "Mali", "capital": "Bamako", "latitude": "12.65", "longitude": "-8"}, {"country": "Malta", "capital": "Valletta", "latitude": "35.88333333", "longitude": "14.5"}, {"country": "Marshall Islands", "capital": "Majuro", "latitude": "7.1", "longitude": "171.383333"}, {"country": "Mauritania", "capital": "Nouakchott", "latitude": "18.06666667", "longitude": "-15.966667"}, {"country": "Mauritius", "capital": "Port Louis", "latitude": "-20.15", "longitude": "57.483333"}, {"country": "Mexico", "capital": "Mexico City", "latitude": "19.43333333", "longitude": "-99.133333"}, {"country": "Moldova", "capital": "Chisinau", "latitude": "47", "longitude": "28.85"}, {"country": "Monaco", "capital": "Monaco", "latitude": "43.73333333", "longitude": "7.416667"}, {"country": "Mongolia", "capital": "Ulaanbaatar", "latitude": "47.91666667", "longitude": "106.916667"}, {"country": "Morocco", "capital": "Rabat", "latitude": "34.01666667", "longitude": "-6.816667"}, {"country": "Mozambique", "capital": "Maputo", "latitude": "-25.95", "longitude": "32.583333"}, {"country": "Namibia", "capital": "Windhoek", "latitude": "-22.56666667", "longitude": "17.083333"}, {"country": "Nepal", "capital": "Kathmandu", "latitude": "27.71666667", "longitude": "85.316667"}, {"country": "Netherlands", "capital": "Amsterdam", "latitude": "52.35", "longitude": "4.916667"}, {"country": "New Caledonia", "capital": "Noumea", "latitude": "-22.26666667", "longitude": "166.45"}, {"country": "New Zealand", "capital": "Wellington", "latitude": "-41.3", "longitude": "174.783333"}, {"country": "Nicaragua", "capital": "Managua", "latitude": "12.13333333", "longitude": "-86.25"}, {"country": "Niger", "capital": "Niamey", "latitude": "13.51666667", "longitude": "2.116667"}, {"country": "Nigeria", "capital": "Abuja", "latitude": "9.083333333", "longitude": "7.533333"}, {"country": "Norway", "capital": "Oslo", "latitude": "59.91666667", "longitude": "10.75"}, {"country": "Oman", "capital": "Muscat", "latitude": "23.61666667", "longitude": "58.583333"}, {"country": "Pakistan", "capital": "Islamabad", "latitude": "33.68333333", "longitude": "73.05"}, {"country": "Palau", "capital": "Melekeok", "latitude": "7.483333333", "longitude": "134.633333"}, {"country": "Panama", "capital": "Panama City", "latitude": "8.966666667", "longitude": "-79.533333"}, {"country": "Papua New Guinea", "capital": "Port Moresby", "latitude": "-9.45", "longitude": "147.183333"}, {"country": "Paraguay", "capital": "Asuncion", "latitude": "-25.26666667", "longitude": "-57.666667"}, {"country": "Peru", "capital": "Lima", "latitude": "-12.05", "longitude": "-77.05"}, {"country": "Philippines", "capital": "Manila", "latitude": "14.6", "longitude": "120.966667"}, {"country": "Poland", "capital": "Warsaw", "latitude": "52.25", "longitude": "21"}, {"country": "Portugal", "capital": "Lisbon", "latitude": "38.71666667", "longitude": "-9.133333"}, {"country": "Puerto Rico", "capital": "San Juan", "latitude": "18.46666667", "longitude": "-66.116667"}, {"country": "Qatar", "capital": "Doha", "latitude": "25.28333333", "longitude": "51.533333"}, {"country": "Romania", "capital": "Bucharest", "latitude": "44.43333333", "longitude": "26.1"}, {"country": "Russia", "capital": "Moscow", "latitude": "55.75", "longitude": "37.6"}, {"country": "Rwanda", "capital": "Kigali", "latitude": "-1.95", "longitude": "30.05"}, {"country": "Saint Helena", "capital": "Jamestown", "latitude": "-15.93333333", "longitude": "-5.716667"}, {"country": "Saint Lucia", "capital": "Castries", "latitude": "14", "longitude": "-61"}, {"country": "Saint Vincent and the Grenadines", "capital": "Kingstown", "latitude": "13.13333333", "longitude": "-61.216667"}, {"country": "Samoa", "capital": "Apia", "latitude": "-13.81666667", "longitude": "-171.766667"}, {"country": "San Marino", "capital": "San Marino", "latitude": "43.93333333", "longitude": "12.416667"}, {"country": "Saudi Arabia", "capital": "Riyadh", "latitude": "24.65", "longitude": "46.7"}, {"country": "Senegal", "capital": "Dakar", "latitude": "14.73333333", "longitude": "-17.633333"}, {"country": "Seychelles", "capital": "Victoria", "latitude": "-4.616666667", "longitude": "55.45"}, {"country": "Sierra Leone", "capital": "Freetown", "latitude": "8.483333333", "longitude": "-13.233333"}, {"country": "Singapore", "capital": "Singapore", "latitude": "1.283333333", "longitude": "103.85"}, {"country": "Slovenia", "capital": "Ljubljana", "latitude": "46.05", "longitude": "14.516667"}, {"country": "Somalia", "capital": "Mogadishu", "latitude": "2.066666667", "longitude": "45.333333"}, {"country": "South Africa", "capital": "Pretoria", "latitude": "-25.7", "longitude": "28.216667"}, {"country": "Spain", "capital": "Madrid", "latitude": "40.4", "longitude": "-3.683333"}, {"country": "Sri Lanka", "capital": "Colombo", "latitude": "6.916666667", "longitude": "79.833333"}, {"country": "Sudan", "capital": "Khartoum", "latitude": "15.6", "longitude": "32.533333"}, {"country": "Suriname", "capital": "Paramaribo", "latitude": "5.833333333", "longitude": "-55.166667"}, {"country": "Swaziland", "capital": "Mbabane", "latitude": "-26.31666667", "longitude": "31.133333"}, {"country": "Sweden", "capital": "Stockholm", "latitude": "59.33333333", "longitude": "18.05"}, {"country": "Switzerland", "capital": "Bern", "latitude": "46.91666667", "longitude": "7.466667"}, {"country": "Syria", "capital": "Damascus", "latitude": "33.5", "longitude": "36.3"}, {"country": "Taiwan", "capital": "Taipei", "latitude": "25.03333333", "longitude": "121.516667"}, {"country": "Tajikistan", "capital": "Dushanbe", "latitude": "38.55", "longitude": "68.766667"}, {"country": "Tanzania", "capital": "Dar es Salaam", "latitude": "-6.8", "longitude": "39.283333"}, {"country": "Thailand", "capital": "Bangkok", "latitude": "13.75", "longitude": "100.516667"}, {"country": "Togo", "capital": "Lome", "latitude": "6.116666667", "longitude": "1.216667"}, {"country": "Tonga", "capital": "Nuku\\u2019alofa", "latitude": "-21.13333333", "longitude": "-175.2"}, {"country": "Tunisia", "capital": "Tunis", "latitude": "36.8", "longitude": "10.183333"}, {"country": "Turkey", "capital": "Ankara", "latitude": "39.93333333", "longitude": "32.866667"}, {"country": "Turkmenistan", "capital": "Ashgabat", "latitude": "37.95", "longitude": "58.383333"}, {"country": "Uganda", "capital": "Kampala", "latitude": "0.316666667", "longitude": "32.55"}, {"country": "Ukraine", "capital": "Kyiv", "latitude": "50.43333333", "longitude": "30.516667"}, {"country": "United Arab Emirates", "capital": "Abu Dhabi", "latitude": "24.46666667", "longitude": "54.366667"}, {"country": "United Kingdom", "capital": "London", "latitude": "51.5", "longitude": "-0.083333"}, {"country": "United States", "capital": "Washington, D.C.", "latitude": "38.883333", "longitude": "-77"}, {"country": "Uruguay", "capital": "Montevideo", "latitude": "-34.85", "longitude": "-56.166667"}, {"country": "Uzbekistan", "capital": "Tashkent", "latitude": "41.31666667", "longitude": "69.25"}, {"country": "Vanuatu", "capital": "Port-Vila", "latitude": "-17.73333333", "longitude": "168.316667"}, {"country": "Venezuela", "capital": "Caracas", "latitude": "10.48333333", "longitude": "-66.866667"}, {"country": "Vietnam", "capital": "Hanoi", "latitude": "21.03333333", "longitude": "105.85"}, {"country": "Yemen", "capital": "Sanaa", "latitude": "15.35", "longitude": "44.2"}, {"country": "Zambia", "capital": "Lusaka", "latitude": "-15.41666667", "longitude": "28.283333"}, {"country": "Zimbabwe", "capital": "Harare", "latitude": "-17.81666667", "longitude": "31.033333"}]'